### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by tomaszeman** [Ramalama2/Voron-2-Mods#1]
Thank you for mention. Will test your version btw. I already added version that fits both e3d and dragon but it's little less stiffer than the original one. (i think your version will fit to e3d too)

**Comment by Ramalama2** [comment]
I seen your new version, actually i like it, just need to print it with 99.8% dimensions 😬
Then it sits better.

Actually the difference between your version and mine is simple...
Mine sits super tight on the heatblock and no wiggling, but is a pain in the a... to mount and unmount...
Yours with 99.8% dimensions, is super nice to mount/unmount, but feels like it isn't super tight on the block ....

I wish we could combine only the positive sides of our both designs 🤦😂

**Comment by Ramalama2** [comment]
Closed
