### ISSUE TITLE
Can't open .stp files in F360

### ISSUE THREAD

**Issue by Alexander-T-Moss** [Ramalama2/Voron-2-Mods#12]
F360 is not importing the files without giving a translation error pointing towards the file being corrupt/incorrectly formatted. Anyway to upload the files as either .step or .f3d ?

**Comment by Ramalama2** [comment]
> F360 is not importing the files without giving a translation error pointing towards the file being corrupt/incorrectly formatted. Anyway to upload the files as either .step or .f3d ?

I can't upload as f3d, which files are you referring to?
Did you tryed redownload them?

**Comment by Alexander-T-Moss** [comment]
Tried re-downloading them but still get this 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54496326/186990858-6bc80ef4-28f8-4986-88b5-f3a9ce35d01f.png">

**Comment by Ramalama2** [comment]
> Tried re-downloading them but still get this <img alt="image" width="1440" src="https://user-images.githubusercontent.com/54496326/186990858-6bc80ef4-28f8-4986-88b5-f3a9ce35d01f.png">

![Screenshot_20220827-000450](https://user-images.githubusercontent.com/6314556/186996717-8b493584-fd7b-4321-867a-ea7d05f7e025.png)

I did just downloaded the step files on my phone, from GitHub....
And i can open them all in cad viewer...
I can open them even in fusion on my pc....

So everything is working, you must have an issue on your side.

**Comment by Alexander-T-Moss** [comment]
I think the issue is downloading them from GitHub as I can't preview the files on any step/stp file viewer

**Comment by Alexander-T-Moss** [comment]
So I tried download the files again but this time by downloading the entire repository and all though I still get an error document they upload fine, so I'll make this as closed now as it sorta works :)

**Comment by Ramalama2** [comment]
Great that it works then 👍😘
