### ISSUE TITLE
Nipple Fix for trident version

### ISSUE THREAD

**Issue by chris155hp** [Ramalama2/Voron-2-Mods#15]
please add the trident version with the nipple fix change =) thanks

**Comment by pheonix3330** [comment]
@chris155hp You probably don't need these anymore, but i'll link my modified files here in case anyone is looking for it later.

I have been using it on my trident and they work great. 

[Front-Idlers_Housing_Trident_Nipple-Fix.zip](https://github.com/Ramalama2/Voron-2-Mods/files/10948885/Front-Idlers_Housing_Trident_Nipple-Fix.zip)

**Comment by Ramalama2** [comment]
Thanks phoenix!
