### ISSUE TITLE
Confused by text on image :-)

### ISSUE THREAD

**Issue by Jaans** [Ramalama2/Voron-2-Mods#16]
Thank you for the LGX lite mod!!

I'm looking at this image from it and I'm somewhat confused:
https://github.com/Ramalama2/Voron-2-Mods/blob/main/SB_LGXlitePCB/Images/3.jpg

Is the text meant to be swapped with the other image? Did you not mean that your new PCB is the better solution? 
Or am I completely misunderstanding something here?

Thanks for your time and sharing this mod

**Comment by cjackson234** [comment]
I think he's saying directly soldering the wires to the board isn't the best way to do it. However, it is the most compact.

**Comment by Ramalama2** [comment]
> I think he's saying directly soldering the wires to the board isn't the best way to do it. However, it is the most compact.

Exactly that xD

And yes the Pic is bad choosen afterwards :-)
