### ISSUE TITLE
Chain_Anchor_2hole.stl can be replaced with stock 3 chain anchor?

### ISSUE THREAD

**Issue by Fett2** [Ramalama2/Voron-2-Mods#18]
Sorry to bring this up as an issue, but I wasn't sure where else to contact you. Can the stock chain anchor be used with the SB_LGXlitePCB? I have a 3 hole cable chain.

**Comment by Loadmaster1** [comment]
The chains only need one of the screws at each end.  I used the most center one on my build.

**Comment by JoaquinBerrios** [comment]
Yes, I'm using the stock three hole chain anchor, and it works fine.

**Comment by Ramalama2** [comment]
Sorry for beeing Late, the Chainanchor is Original, so the default ones fits!
