### ISSUE TITLE
SB_LGXlitePCB - Recommend cutting all pins flush on main hotend PCB to avoid shorts

### ISSUE THREAD

**Issue by JoaquinBerrios** [Ramalama2/Voron-2-Mods#19]
When using the mounting system from this repo on my main hotend PCB, the pins on the back of the board shorted against the metal housing of the motor. I was lucky that the PSU overcurrent protection tripped and nothing was damaged. 

I would recommend noting on the instructions that it may be a good idea to trim all pins from the main hotend board flush (or at least the ones for the main plug near the motor housing) and that it may be a good idea to add some insulation between the PCB and the motor for additional safety. I just covered pins on the back of my board with a couple of layers of kapton tape after trimming the pins flush.

**Comment by Ramalama2** [comment]
I did the same xD
And ill add that to the description, thanks!
