### ISSUE TITLE
Option_without_LGXlite-FanPCB - Works

### ISSUE THREAD

**Issue by kwojcik9** [Ramalama2/Voron-2-Mods#24]
This isn’t an issue, just wanted to say Option_without_LGXlite-FanPCB front cover works like a charm.  Thanks so much!

**Comment by tagy** [comment]
I'm guessing you don't screw the PCB down with this version? As the holes will not line up? Is that right?

**Comment by kwojcik9** [comment]
Hmm weird, I was able to screw down the PCB.  I know there are a few different versions.
