### ISSUE TITLE
Mulit body front covers for multi color prints 

### ISSUE THREAD

**Issue by chris155hp** [Ramalama2/Voron-2-Mods#29]
if you could make a multi body idler covers so that the logo can be printed a different color that would be amazing. Multi body has really become mainstream since the release of V0.2. The 0.2 skirts have mulit body in the Voron official git

**Comment by scul86** [comment]
I did some work on the Henrikssn Cover to make them multibody and eliminate the pin holes.

However, I have not printed these yet (up soon), but they match the other 'stock' covers in dimension and lack of pin holes.
[Henrikssn_Cover_multibody.zip](https://github.com/Ramalama2/Voron-2-Mods/files/12089850/Henrikssn_Cover_multibody.zip)
