### ISSUE TITLE
ipt files are excluded from Fusion360 (non commercial licence)

### ISSUE THREAD

**Issue by ocgeek** [Ramalama2/Voron-2-Mods#3]
Dear Rama,
for CAD would it be possible please to **avoid** **.ipt files**.

Those extensions dropped out of Fusion 360 non commercial license; that restricts a lot their usability from others.

Many thanks

**Comment by Ramalama2** [comment]
Hi, that's why i provide step files either.
Im working with inventor, so i can only provide "ipt" as "real source" files.
The only other option for everyone else are the step files, but that isn't souce, just normal cad files.

**Comment by Ramalama2** [comment]
However, im gonna close this as "resolved".

1. Im sorry, but i will not starting to learn Fusion (or to loose time with that), to make people happy with Fusion Sources xD
2. Im trying always to provide all source files and Step files as backup.
3. Feel free to ask me simply if you need any other/special/whatever Source/Cad files, i can provide everything that Inventor can export.
4. Inventor can't export sadly f3d... Dont ask me why, its totally stupid, Inventor and Fusion are both made by Autodesk xD

Thanks & Cheers :-)
