### ISSUE TITLE
Cura Slicer Profil

### ISSUE THREAD

**Issue by Martin11180** [Ramalama2/Voron-2-Mods#32]
Hello
Thanks for your Voron 2 mods
You can also make your Cura profile for ABS available via Github
It's hard to find on the web

greet
Martin

**Comment by Ramalama2** [comment]
Hey Martin, im sorry, im not using any voron printer anymore, since the time i went the community.

I've switched to a Bambu x1c and this repository is more like an archive.
Didn't wanted to be an ass and delete it.

Sorry & Cheers
