### ISSUE TITLE
The link to Hartik mod in the readme has changed

### ISSUE THREAD

**Issue by SergeDubovsky** [Ramalama2/Voron-2-Mods#33]
from 
https://github.com/hartk1213/MISC/tree/main/Voron%20Mods/Voron%202/2.4/Voron2.4_GE5C 
to:
https://github.com/hartk1213/MISC/tree/main/Voron%20Mods/Voron%202-Trident/2.4/Voron2.4_GE5C

**Comment by Ramalama2** [comment]
I'll have another idea, ill change the repository to depricated.
The last update i did was like 2 years ago anyway and im not planning to get back into the Voron community or do any mods or changes either.

Dont understand me wrong, it was a cool time, cool community and everything, but life goes on xD

Cheers :-)
