### ISSUE TITLE
Locator pins are a little fragile and easily broken

### ISSUE THREAD

**Issue by ningpj** [Ramalama2/Voron-2-Mods#4]
Ive printed a few of these now and always manage to break off the top locator pins at the unsecured end.  Would be helpful if you could revise these to make them a little more robust

**Comment by ningpj** [comment]
I modified the base and changed the pins to holes I can use short metal pins to locate the tensioner end cap.  No more broken pins for me ;-)

**Comment by Ramalama2** [comment]
Not everyone has metal short pins 🙈
But i will think how to improve that

**Comment by mvdveer** [comment]
Had the same issue - just enlarged the locating holes on the cover

**Comment by Ramalama2** [comment]
There is now a nipplefix version to test 🙈🤣

**Comment by ningpj** [comment]
Finally got around to testing nipplefix....works really well - case closed :-)
