### ISSUE TITLE
Trident Front idlers

### ISSUE THREAD

**Issue by TadasMit** [Ramalama2/Voron-2-Mods#6]
Hi. I made a mod for your front idlers to better fit the Trident. Are you interested in posting in your rep? If so, let me know how to send the files to you. 
I have printed, assembled the new idlers fits well, works well :) 

Thanx!

![Screenshot 2022-02-19 195830](https://user-images.githubusercontent.com/100053391/154824306-5008876f-8d3b-44a0-8b47-77629ca8e673.jpg)
![Screenshot 2022-02-19 195851](https://user-images.githubusercontent.com/100053391/154824307-73e764ed-2b1b-4d5c-b998-4df7e8cea852.jpg)
![Screenshot 2022-02-19 200227](https://user-images.githubusercontent.com/100053391/154824378-72cab3b1-1420-4f1a-a8a3-7285627bab4e.jpg)

**Comment by Ramalama2** [comment]
Awesome, the only problem is, that you catched me in my holidays 🙈If you have discord you can write me there Rama#6392, if not just make a pull request.Thanks for the work 👍😂Am 20.02.2022 02:06 schrieb TadasMit ***@***.***>:
Hi. I made a mod for your front idlers to better fit the Trident. Are you interested in posting in your rep? If so, let me know how to send the files to you.
I have printed, assembled the new idlers fits well, works well :)
Thanx!

**Comment by aksqlt** [comment]
> Hi. I made a mod for your front idlers to better fit the Trident. Are you interested in posting in your rep? If so, let me know how to send the files to you. I have printed, assembled the new idlers fits well, works well :)
> 
> Thanx!
> 
> 

Hi TadasMit
would you mind to share your stl files with me? I'm building Trident and made similar modifications but forgot about door 
 clearance :(
 thanks
 -Alex

**Comment by TadasMit** [comment]
[Front Idlers.zip](https://github.com/Ramalama2/Voron-2-Mods/files/8240587/Front.Idlers.zip)
Hi Alex,

I am attaching zip files for Front Idlers (Trident mod). I also sent files to Rama; hopefully, he will have time to put them on his Github :)

**Comment by aksqlt** [comment]
> [Front Idlers.zip](https://github.com/Ramalama2/Voron-2-Mods/files/8240587/Front.Idlers.zip) Hi Alex,
> 
> I am attaching zip files for Front Idlers (Trident mod). I also sent files to Rama; hopefully, he will have time to put them on his Github :)

Thank you!!!

**Comment by Ramalama2** [comment]
@TadasMit Idlers are merged now. So im going to Close this issue :-)

Note: The Repo was updated and no one needs to reprint the Trident Idlers, if you are using Tadas Version already from above!
Everyone else that use 2.4 Idlers on Trident, should switch.

Thanks again @TadasMit and everyone else!
