### ISSUE TITLE
5M 22mm  available at MacMaster-Carr

### ISSUE THREAD

**Issue by NikosSprocket** [Ramalama2/Voron-2-Mods#7]
Not really an issue just an FYI.

MacMaster-Carr carries 5M 22mm 18-8 Stainless Steel Button Head Hex Drive Screws for $11.00 pack of 100.
Can be found at this [link](https://www.mcmaster.com/92095A482).

Also, M5 washers DIN 433 18-8 Stainless Steel from MacMaster-Carr at [link](https://www.mcmaster.com/98689A114) for $3.71 pack of 100.

Also, I have used your latest STEP files (awesome! Thank You!) and assembled them in Fusion360. I have put some samples:
[Pic1](https://bricksafe.com/files/NikosSprocket/fusion-360/2022-04-02_00h48_07.png/1280x1512.png)
[Pic2](https://bricksafe.com/files/NikosSprocket/fusion-360/2022-04-02_00h51_32.png/1280x1600.png)
[Pic3](https://bricksafe.com/files/NikosSprocket/fusion-360/2022-04-02_00h52_54.png/1280x1755.png)

Late me know if you would like some larger or you can use these.

Cheers!

**Comment by Ramalama2** [comment]
> Not really an issue just an FYI.
> 
> MacMaster-Carr carries 5M 22mm 18-8 Stainless Steel Button Head Hex Drive Screws for $11.00 pack of 100. Can be found at this [link](https://www.mcmaster.com/92095A482).
> 
> Also, M5 washers DIN 433 18-8 Stainless Steel from MacMaster-Carr at [link](https://www.mcmaster.com/98689A114) for $3.71 pack of 100.
> 
> Also, I have used your latest STEP files (awesome! Thank You!) and assembled them in Fusion360. I have put some samples: [Pic1](https://bricksafe.com/files/NikosSprocket/fusion-360/2022-04-02_00h48_07.png/1280x1512.png) [Pic2](https://bricksafe.com/files/NikosSprocket/fusion-360/2022-04-02_00h51_32.png/1280x1600.png) [Pic3](https://bricksafe.com/files/NikosSprocket/fusion-360/2022-04-02_00h52_54.png/1280x1755.png)
> 
> Late me know if you would like some larger or you can use these.
> 
> Cheers!

Hey Niko, thanks for the hint. I will add the info and your Fusion Pics to the Repo.
Just if possible, could you share your fusion sources either, so i wont get penetrated so often, that i release only inventor files and no fusion files :-( (Sadly im working only with inventor and not fusion) xD

**Comment by NikosSprocket** [comment]
Hi!

Of course; the only problem is that I am new to GitHub and I not familiar with uploading files etc. I have an account and familiar with unix svn but new to GitHub. Can you tell me how to upload the Fusion360 file to GitHub?

btw, the MiSUMi RBPB5 is press fitted to the Z-Joint and the build in groove in the Z-joint is sufficient to hold the bearing from moving up/down?

Cheers!
Nikos

**Comment by Ramalama2** [comment]
A bit late but:
For 1. you can simply send me over discord, thats the easy way, or make a pull request, for that you need to fork the repo etc 🙈

For 2. let's hope that picture is self explaining. An ender 3 weights for sure a lot more as a gantry 🙈
And that's only one RBPB5, you have 4 of them on the gantry 😂
![IMG_20210918_160021](https://user-images.githubusercontent.com/6314556/177022997-4a651b83-8012-45c3-b0c7-938e53f86dbb.jpg)
![IMG_20210918_160046](https://user-images.githubusercontent.com/6314556/177022998-93c163c3-e75f-46d4-b1ca-c2755016e1bd.jpg)
