### ISSUE TITLE
Rename STLs to show x2 and accent color

### ISSUE THREAD

**Issue by rlaferla** [Ramalama2/Voron-2-Mods#8]
Please rename Trident and 2.4 STLs to show x2 and accent color in the filename.

i.e.  [a]_ for accent color and _x2.stl for print two of these.

<img width="179" alt="image" src="https://user-images.githubusercontent.com/1135694/162801978-341bcdd9-cfac-4394-99d1-e37b16a7c19c.png">

**Comment by Ramalama2** [comment]
I don't see any point in that, sorry :-)

I mean its basically always only 3-4 Stls, and in general very small mods. Not a big project where you can loose overview :-)
But thx & Cheers :-)
